---
- name: Testing andrewrothstein.bbr
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'bbr --version'
      ansible.builtin.command: bbr --version
      changed_when: false
      register: bbr_test_output
    - name: Output of 'bbr --version'
      ansible.builtin.debug:
        msg: '{{ bbr_test_output.stdout }}'
